# Generated by Django 3.2 on 2023-11-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231102_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permission',
            field=models.CharField(default='일반', max_length=100),
        ),
    ]
