# Generated by Django 3.2 on 2023-11-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumb_image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('file_upload', models.FileField(blank=True, upload_to='tube/files/%Y/%m/%d/')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_contents',
            field=models.ManyToManyField(blank=True, to='tube.PostContent'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ManyToManyField(blank=True, to='tube.PostImage'),
        ),
    ]
