# Generated by Django 3.2 on 2023-11-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_rename_name_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tube.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_contents',
            field=models.ManyToManyField(blank=True, related_name='post_contents', to='tube.PostContent'),
        ),
    ]
