# Generated by Django 3.2 on 2023-11-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0016_auto_20231106_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_author',
        ),
    ]
