# Generated by Django 3.2 on 2023-11-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0020_posthistory_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='file_upload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
