# Generated by Django 3.2 on 2023-11-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='권한',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='부서',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='성명',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='직급',
            new_name='position',
        ),
    ]
