# Generated by Django 3.2 on 2023-11-02 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0002_auto_20231102_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='posts',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='posts',
            new_name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='read_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
