# Generated by Django 3.2 on 2023-11-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0006_auto_20231102_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='post',
            new_name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(db_index=True, default='bug', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tube.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tube.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_contents',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tube.PostContent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tube.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
