# Generated by Django 3.2 on 2023-11-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_auto_20231102_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='tube/files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tube.post'),
        ),
    ]
