# Generated by Django 3.2 on 2023-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_auto_20231102_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_contents',
            field=models.ManyToManyField(blank=True, related_name='related_posts', to='tube.PostContent'),
        ),
    ]
