# Generated by Django 3.2 on 2023-11-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0011_post_post_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_contents',
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_contents', to='tube.postcontent'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tube.post'),
        ),
    ]
