# Generated by Django 3.2 on 2023-11-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0012_auto_20231102_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_content',
        ),
        migrations.AddField(
            model_name='post',
            name='post_contents',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tube.PostContent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tube.Tag'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcontent', to='tube.post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttag', to='tube.post'),
        ),
    ]
