# Generated by Django 3.2 on 2023-11-02 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0014_auto_20231102_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='finecheck',
            field=models.TextField(db_index=True, default='BUG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='bug', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='tags', to='tube.Tag'),
        ),
        migrations.CreateModel(
            name='ClearPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_contents', models.TextField()),
                ('category', models.CharField(default='bug', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_posts_written', to=settings.AUTH_USER_MODEL)),
                ('read_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_posts_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
