# Generated by Django 3.2 on 2023-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0017_remove_post_read_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='tags',
            field=models.TextField(),
        ),
    ]
