# Generated by Django 3.2 on 2023-11-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0019_auto_20231107_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthistory',
            name='post_comments',
            field=models.TextField(default=''),
        ),
    ]
