# Generated by Django 3.2 on 2023-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0021_alter_postcontent_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
