# Generated by Django 3.2 on 2023-11-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0022_alter_postcontent_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hisimg', to='tube.posthistory')),
            ],
        ),
        migrations.AddField(
            model_name='posthistory',
            name='images',
            field=models.ManyToManyField(related_name='posts', to='tube.Image'),
        ),
    ]
